### ISSUE TITLE
HASS 202310版添加外链除了新页面外，其他3个选项都是提示拒绝访问

### ISSUE THREAD

**Issue by XtosX** [shaonianzhentan/panel_iframe#10]
Home Assistant 2023.10.0
Supervisor 2023.10.0
Operating System 10.5
前端版本： 20231002.0 - lates

**Comment by shaonianzhentan** [comment]
拒绝访问，说明当前添加的网站不支持嵌套使用，可以使用打开新页面的方式加入到HA中
