### ISSUE TITLE
希望可以支持本地图片

### ISSUE THREAD

**Issue by jdbwlj** [shaonianzhentan/panel_iframe#2]
icon图标太难找了，填上容器路径/icon/docker.png，上传文件到真实路径/opt/ha/icon/docker.png,这种方式添加图标

**Comment by shaonianzhentan** [comment]
> icon图标太难找了，填上容器路径/icon/docker.png，上传文件到真实路径/opt/ha/icon/docker.png,这种方式添加图标

HomeAssistant侧边栏icon不支持图片，可在下面链接中找一个自己喜欢的复制粘贴即可
https://unpkg.com/@mdi/font@latest/preview.html

在浏览器中使用快捷键`Ctrl+F`可快速查找
![image](https://user-images.githubusercontent.com/5294022/200987062-3fb48df7-c762-4652-bec0-7681fd9fe667.png)
