### ISSUE TITLE
侧边栏管理页面打不开

### ISSUE THREAD

**Issue by airwb** [shaonianzhentan/panel_iframe#3]
![image](https://user-images.githubusercontent.com/78411049/202088931-7103456a-1c2a-417c-b161-c3bd7ab8baa0.png)

**Comment by shaonianzhentan** [comment]
一般出现这种情况，就是你自己配置的问题

[请关注微信公众号，查看详细教程](https://mp.weixin.qq.com/s?__biz=MjM5MzUxODIwOQ==&mid=2650169739&idx=1&sn=de7e1e4571ab6067d2cdd99d25ce56fa&chksm=be97066589e08f7380bcabc8605c573624919f0c62b32825bcb523ca4213e5f675a899226bdc&scene=178&cur_album_id=2225049427352797188&rd2werd=1&key=f6a743ba4f21fa7f59731f433856d795438c797e57b46889d26b895eabc32900acbe29ba36df64c14402544b5d284b7c071ad4a3654f31dd9d32f696ccc8466a1d2287d36cf19ad6529a66fd7d79b09c90814061f98559297c56ad21d336fa49442fcfed40866f987a10856f7e534fe196ed1404c24ad35f12c28d4962476e48&ascene=7&uin=NDQ5MTgyMDgw&devicetype=Windows+10+x64&version=6308001f&lang=zh_CN&exportkey=n_ChQIAhIQXVE3cl16GY7LGWqqp4TX8xLcAQIE97dBBAEAAAAAAL4uIa9AFNgAAAAOpnltbLcz9gKNyK89dVj08QwPiq3tC62q%2FpgFlV13aUi4o3IRniYYdNhXISqMEtDuWkDBxj3P4yoKseapSdFmdoGGTGOGTe4IDKRsOP4VcaB0eDfB5KMChZC7qIaeONFHlaouQ7gQHFvFXrSEslfNpwjtNfmghxz90gNN4LFIkcwAJ0LJ2NKrBuiok7TsT2Hagc8epXqkPJ%2F%2FHfe7SEroWbcsj8Rl6CPhFJ5D9u8JfudOb%2BTqErJyjNBzzzrLW47D6o5pXY0%3D&acctmode=0&pass_ticket=AFDWq8SkCPA1UbXOhj51sDXLoQLXX8TP%2FiLN52NSSvu8dhrejvMLIvldce6Qo8IT&wx_header=0&fontgear=2)
