### ISSUE TITLE
面板显示404: Not Found

### ISSUE THREAD

**Issue by airwb** [shaonianzhentan/panel_iframe#4]
按照教程部署好之后，显示404: Not Found，请问是什么原因

**Comment by shaonianzhentan** [comment]
> 按照教程部署好之后，显示404: Not Found，请问是什么原因

问题是你的链接没有配置正确
---
如果你想很好的得到帮助，最好能附上一些配置过程的图片，让我知道你想做什么，以及怎么做的

**Comment by airwb** [comment]
在hacs里面安装panel_iframe，重启之后在集成-侧边栏面板里面进行配置，链接：panel_iframe，提交之后左边可以看到侧边栏面板，点进去之后右侧窗口显示404 not found。
![Snipaste_2022-11-19_12-04-02](https://user-images.githubusercontent.com/78411049/202833454-f6139333-12a2-48af-90ba-f1e96e7a4c78.png)

**Comment by shaonianzhentan** [comment]
我觉得你应该是没有认真看教程，以至于乱填链接地址导致404
---
这里已经回复给你教程地址了 https://github.com/shaonianzhentan/panel_iframe/issues/3
