### ISSUE TITLE
使用系统内部功能菜单时建议使用相对路径进行配置

### ISSUE THREAD

**Issue by peakliuz** [shaonianzhentan/panel_iframe#5]
### 使用场景
在ha可以内外网同时访问的情况下,侧边栏面板只支持一个链接配置,所以只能将url链接配置为外网访问的url链接
外网访问速度始终没有内网快,所以在内网环境,如果都用内网链接访问便是最好

### 初步思路
例如我的ha url路径为 `http://192.168.1.123:8127/`,我想把内置的`场景自动化`页面(`http://192.168.1.123:8127/config/automation/dashboard`)加入到侧边栏,只需取相对路径即可,插件会自动取当前页面url中的ip和端口作为路径前缀拼接配置的路径地址

<img width="452" alt="image" src="https://user-images.githubusercontent.com/75781948/211698351-e49ce61d-eb55-4899-be37-074d5f726f13.png">

**Comment by shaonianzhentan** [comment]
已支持此功能，详情教程可以在`HomeAssistant家庭助理`公众号中搜索`侧边栏面板管理`
