### ISSUE TITLE
安装成功，配置完，前端显示异常

### ISSUE THREAD

**Issue by wyz2019** [shaonianzhentan/panel_iframe#7]
我设置了显示模式为新页面，然后链接打开后是这个样子的。

http://192.168.2.86:8123/panel_iframe_www/www.baidu.com

<img width="405" alt="image" src="https://user-images.githubusercontent.com/57739555/231962108-2a21a0a9-db78-44e4-9be4-6de860b327b1.png">

**Comment by wyz2019** [comment]
<img width="854" alt="image" src="https://user-images.githubusercontent.com/57739555/231962223-7cedb579-7c41-40dd-bc6f-4a0813c70deb.png">

**Comment by shaonianzhentan** [comment]
正确的链接应该是：https://www.baidu.com

详情教程可以在`HomeAssistant家庭助理`公众号中搜索`侧边栏面板管理`
