### ISSUE TITLE
[建议] 每次点击打开自定义的侧边栏链接时，界面都会白一下显示链接然后再跳转对面的链接页面

### ISSUE THREAD

**Issue by lxz946786639** [shaonianzhentan/panel_iframe#8]
希望优化一下这个交互，显示加载中之类的，不要出现这个闪屏。
如图：
![image](https://github.com/shaonianzhentan/panel_iframe/assets/40382425/4b287067-1ae7-40f0-a9dd-26fcf45d849a)

**Comment by shaonianzhentan** [comment]
已调整
