### ISSUE TITLE
panel_iframe 请求404

### ISSUE THREAD

**Issue by catchfishday** [shaonianzhentan/panel_iframe#9]
您好，帮忙看看为啥每次刷新页面这个地址请求总是返回404
http://x.x.x.x:8123/panel_iframe_www/panel_iframe.js?v=2023.5.25

![image](https://github.com/shaonianzhentan/panel_iframe/assets/12185015/d2137403-7cf7-4b34-a2f2-b25eea3f6129)

**Comment by shaonianzhentan** [comment]
已修复

**Comment by catchfishday** [comment]
> 已修复

谢谢
